@endpoint = https://e7x2rt5kbb.execute-api.eu-west-1.amazonaws.com/prod/
GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces?spaceId=ff5540b3-7380-4b16-b5f0-30e798ae723c
###

GET {{endpoint}}/spaces
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "Location": "London",
    "name": "3rd Best Location"
}
###
