@endpoint = https://e7x2rt5kbb.execute-api.eu-west-1.amazonaws.com/prod/
GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces?spaceId=bea51db0-ece1-4bfd-a5ea-f6fdf8ccbdc4
###

GET {{endpoint}}/spaces
###

GET {{endpoint}}/spaces?location=London
###

GET {{endpoint}}/spaces?location=Paris
###

GET {{endpoint}}/spaces
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "Location": "London",
    "name": "3rd Best Location"
}
###
