@endpoint = https://e7x2rt5kbb.execute-api.eu-west-1.amazonaws.com/prod/
GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces?spaceId=bea51db0-ece1-4bfd-a5ea-f6fdf8ccbdc4
###

GET {{endpoint}}/spaces
###

GET {{endpoint}}/spaces?location=London
###

GET {{endpoint}}/spaces?location=Paris
###

GET {{endpoint}}/spaces
###

GET {{endpoint}}/spaces?spaceId=2acf4b91-44c8-4ae1-9cde-258b6f1b8616
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Paris",
    "name": "Interesting for shopping"
}
###

PUT {{endpoint}}/spaces?spaceId=2acf4b91-44c8-4ae1-9cde-258b6f1b8616
Content-Type: application/json

{
    "location": "Paris-Ile"
}
###

DELETE {{endpoint}}/spaces?spaceId=2acf4b91-44c8-4ae1-9cde-258b6f1b8616
###